### ISSUE TITLE
[QUESTION] TLS 1.3 issues.

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#39] opened 2024-03-03 06:31 UTC
Azure TLS seems to use TLS 1.2 which is fine since a majority of the web uses it, but most modern browsers are using TLS 1.3. Ja3 signatures from newer browsers cause errors as azuretls doesn't support it. I am requesting TLS 1.3 as it is newer, more efficient, safer, and would provide a higher reputation when connecting through sites like cloudflare

**Comment by Noooste** [comment] 2024-03-05 11:22
Hi, I'm currently using wireshark, and it's on TLSv1.3, do you have a screen to display TLSv1.2?

**Comment by VegieIsCute** [comment] 2024-03-05 21:09
That's odd, maybe TLS1.3 is supported but spoofing HTTP2 to a client of TLS1.3 fails,

Here is Firefox using TLS1.3
```
session := azuretls.NewSession()
	defer session.Close()

	err := session.ApplyJa3("771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28-65037-41,29-23-24-25-256-257,0", azuretls.Firefox)
	if err != nil {
		log.Fatal(err)
		return
	}

	err = session.ApplyHTTP2("1:65536,4:131072,5:16384|12517377|3:0:0:201,5:0:0:101,7:0:0:1,9:0:7:1,11:0:3:1,13:0:0:241|m,p,a,s")
	if err != nil {
		log.Fatal(err)
		return
	}

	response, err := session.Get("https://tls.peet.ws/api/all")

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body))
	}
```

It outputs: remote error: tls: unexpected message

Meanwhile here is Firefox using TLS1.2 (I am forcing it by adjusting the security.tls.version.max flag in about:config)
```
session := azuretls.NewSession()
	defer session.Close()

	err := session.ApplyJa3("771,49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-28,29-23-24-25,0", azuretls.Firefox)
	if err != nil {
		log.Fatal(err)
		return
	}

	err = session.ApplyHTTP2("1:65536,4:131072,5:16384|12517377|3:0:0:201,5:0:0:101,7:0:0:1,9:0:7:1,11:0:3:1,13:0:0:241|m,p,a,s")
	if err != nil {
		log.Fatal(err)
		return
	}

	response, err := session.Get("https://tls.peet.ws/api/all")

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body))
	}```

The request completes successfully.

**Comment by VegieIsCute** [comment] 2024-03-05 21:10
Clicked the wrong button by accident.

**Comment by Noooste** [comment] 2024-03-05 21:42
For the first JA3, this doesn't work because, in the extension part, you've put the extension number `41` which is used to resume the TLS connection. Since you want a completely new TLS connection, you need to remove this extension: I've tested it and it establishes the connection with TLSv1.3.

Here is the JA3:
`771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28-65037,29-23-24-25-256-257,0`

**Comment by VegieIsCute** [comment] 2024-03-05 21:49
I can't seem to find a 41 in the original string, did you mistype the number?

**Comment by VegieIsCute** [comment] 2024-03-05 21:51
Btw, the new JA3 you provided me produces a different ja3 hash, which kind of beats the point of spoofing it. Any workarounds?

**Comment by Noooste** [comment] 2024-03-05 21:52
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28-65037-`41`,29-23-24-25-256-257,0

> I can't seem to find a 41 in the original string, did you mistype the number?

**Comment by Noooste** [comment] 2024-03-05 21:55
Try to close and restart your firefox, and go to https://tls.peet.ws/api/all, you will see that `41` won't be there

**Comment by VegieIsCute** [comment] 2024-03-05 21:57
Okay, I see now thanks for clarifying the issue. It seems that the hashes now match.

**Comment by VegieIsCute** [comment] 2024-03-05 22:13
I just noticed an issue.

connecting to https://tls.peet.ws/api/all with the JA3 you gave me works, but trying to connect to https://www.cloudflare.com/cdn-cgi/trace outputs tls: error decoding message. Could this be due to a missing cipher suite in go?

**Comment by Noooste** [comment] 2024-03-06 15:30
Could you give me a code example, I can't reproduce this behavior on my side

**Comment by VegieIsCute** [comment] 2024-03-06 16:41
```session := azuretls.NewSession()
	defer session.Close()

	err := session.ApplyJa3("771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28-65037,29-23-24-25-256-257,0", azuretls.Firefox)
	if err != nil {
		log.Fatal(err)
		return
	}

	err = session.ApplyHTTP2("1:65536,4:131072,5:16384|12517377|3:0:0:201,5:0:0:101,7:0:0:1,9:0:7:1,11:0:3:1,13:0:0:241|m,p,a,s")
	if err != nil {
		log.Fatal(err)
		return
	}

	response, err := session.Get("https://www.cloudflare.com/cdn-cgi/trace")

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body))
	}```

Using TLS1.3

If you change the cloudflare link to https://tls.peet.ws/api/all it works, might have something to do with server cipher suites not sure.

**Comment by Noooste** [comment] 2024-03-06 18:14
Thanks for sharing, this will be fixed.

**Closed** 2024-03-06 18:16 UTC
